"use client";

import { EnrollMFAForm } from "../form/enroll-mfa-form";

export function EnrollMFAView() {
  return (
    <div className="bg-transparent mb-20 flex flex-col items-center pt-10 px-4">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 w-full max-w-xl p-4 bg-transparent">
        <div className="space-y-4">
          <h1 className="text-2xl font-bold text-center text-[#26045D]">
            Keep your account secured
          </h1>
          <p className="text-sm text-start text-gray-600">
            To enhance your account security, set up Multi-Factor Authentication
            (MFA). Follow these steps:
          </p>
          <ol className="text-gray-600 text-sm list-decimal list-inside mb-4">
            <li>
              On your phone, install an authenticator app like{" "}
              <strong>Google Authenticator</strong> or <strong>Authy</strong>.
            </li>
            <li>Use the app to scan the QR code below.</li>
            <li>
              Enter the 6-digit code generated by the app to complete the setup.
            </li>
          </ol>
        </div>
        <EnrollMFAForm />
      </div>
    </div>
  );
}
